import React from "react";
import Head from 'next/head'
import Navbar from '../components/navbar'
import Layout from '../components/layout'
import MovieList from '../components/movie-list'
import MovieCard from '../components/movie-card'
import MovieFilter from '../components/movie-filter'
import FilterDropdown from '../components/filter-dropdown'
import orderBy from 'lodash.orderby'
export async function getStaticProps(context) {
  const res = await fetch(`https://imdb-api.com/en/API/MostPopularMovies/k_wc9gw5le`)
  const data = await res.json()

  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }
}


export default function Home({data}) {
  const [sortValue, setSort] = React.useState('rank:asc');
  const [movies, setMovies] = React.useState(data.items);

  const handleChange = ev =>{
    const sort_arr = ev.target.value.split(":")
    if(sort_arr[0] === 'rank') { 
      setMovies(data.items)
    } else {
      const sortedList = orderBy({...data.items}, [sort_arr[0]],[sort_arr[1]]);
      setMovies(sortedList)
    }
    setSort(ev.target.value)
    
    
  }
  return (
    <div className="container">
      <Head>
        <title>Coding Test Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <Layout>
        <Navbar />
        <MovieFilter>
          <FilterDropdown onChange={handleChange} value={sortValue} />
        </MovieFilter>
        <MovieList title="Most Popular Movies">
          {movies.map(movie => <MovieCard key={movie.id} movie={movie} />)}
        </MovieList>
      </Layout>
    </div>
  )
}
